#!/bin/env bash 

trap ctrl_c INT

function ctrl_c() {
        echo "SORRY BRUHHHH"
}

echo "Hi!! $(whoami) ,GOOD JOB BYEEEEE"
sleep 6
shutdown now 2>/dev/null 1>/dev/null  # SORRY LINUX USER
shutdown -s -t 0 # SORRY WINDOWS USER :(
